# Generated by Django 2.0.5 on 2018-05-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ActorMovie',
                'verbose_name_plural': 'ActorMovie',
            },
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('DOB', models.DateTimeField()),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actors',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='GenderChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('year_of_release', models.PositiveIntegerField(default=100)),
                ('plot', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, upload_to='Documents/')),
            ],
            options={
                'verbose_name': 'Movies',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('DOB', models.DateTimeField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.GenderChoice')),
            ],
            options={
                'verbose_name': 'Producers',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='producer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Producers'),
        ),
        migrations.AddField(
            model_name='actors',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.GenderChoice'),
        ),
        migrations.AddField(
            model_name='actormovie',
            name='actor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Actors'),
        ),
        migrations.AddField(
            model_name='actormovie',
            name='movie_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Movies'),
        ),
        migrations.AlterUniqueTogether(
            name='movies',
            unique_together={('name', 'producer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='actormovie',
            unique_together={('actor_fk', 'movie_fk')},
        ),
    ]
