# Generated by Django 2.0.5 on 2018-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='DOB',
            field=models.DateField(),
        ),
    ]
